version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31.0
    restart: always
    ports:
      - "4499:4499"
    environment:
      PRISMA_CONFIG: |
        port: 4499
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.6
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: